print('onlinefeature1')
print('onlinefeature2')
print('onlinefeature3')
print('Local feauture4')
print('Local feauture5')
print('Local feauture6')
print('onlinefeature7')
print('onlinefeature8')
print('onlinefeature9')
